export const keywords = [
  "Rida Najeeb",
  "Rida",
  "Najeeb",
  "Rida1401",
  "rn-portfolio.vercel.app",
  "najeebrida14@gmail.com",
  "linkedin/in/rida-n-87311a367",
  "Rida Najeeb portfolio",
  "Rida Najeeb developer",
  "Rida Najeeb software engineer",
  "Rida Najeeb web developer",
  "Rida Najeeb cloud engineer",
  "Rida Najeeb full-stack developer",
  "Rida Najeeb projects",
  "Rida Najeeb resume",
  "Rida Najeeb contact",

  "student developer portfolio",
  "web developer Hyderabad",
  "frontend developer India",
  "full-stack engineer portfolio",
  "open source web developer",
  "Next.js frontend portfolio",
  "React developer personal site",
  "software engineer portfolio",
  "AI developer portfolio",
  "Machine Learning Engineer",
  "Content Development Tech",
  "technical question curator",
  "data bug resolution",
  "cloud developer",
  "DevOps enthusiast",
  "entry-level software engineer",
  "junior web developer",

  "C programming",
  "C++ programming",
  "Java developer",
  "JavaScript developer",
  "TypeScript developer",
  "Python developer",
  "HTML/CSS development",

  "React.js developer",
  "Next.js developer",
  "Framer Motion animations",
  "Tailwind CSS design",
  "Bootstrap framework",
  "ShadCN UI components",
  "responsive web design",
  "UI/UX development",
  "modern UI development",
  "Next.js Server Components",
  "Next.js Client Components",
  "CSS Modules",
  "SCSS",
  "Redux state management",

  "Express.js backend",
  "API Design",
  "MongoDB database",
  "Oracle SQL",
  "MySQL database",
  "PostgreSQL database",
  "Prisma ORM",
  "drizzle ORM",
  "serverless functions",
  "Next.js API routes",
  "REST API development",
  "GraphQL API",
  "WebSockets",

  "Machine Learning",
  "Deep Learning",
  "Generative AI",
  "Large Language Models",
  "Natural Language Processing",
  "Prompt Engineering",
  "AI model fine-tuning",
  "TensorFlow",
  "PyTorch",

  "Git version control",
  "GitHub collaboration",
  "Postman API testing",
  "Jest testing setup",
  "API integration with Next.js",
  "Firebase hosting",
  "Netlify deployment",
  "Vercel deployment",
  "Docker basics",
  "CI/CD with GitHub Actions",
  "VS Code extensions",
  "Webpack",
  "Vite",
  "Figma UI/UX design",

  "personal portfolio website Next.js",
  "EmailJS integration",
  "Framer Motion portfolio",
  "SEO optimization portfolio",
  "structured metadata website",
  "Open Graph tags SEO",
  "performance optimization web",
  "accessibility best practices",
  "AI projects portfolio",
  "real-world React projects",
  "full-stack project examples",
  "web application development",

  "HackerRank Problem Solving Certificate",
  "Scientific Computing with Python FreeCodeCamp",

  "best student portfolios 2025",
  "react portfolio example 2025",
  "Next.js app directory project",
  "modern web development portfolio",
  "best open source portfolio projects",
  "developer website examples",
  "personal web developer site",
  "interactive resume website",
  "coding portfolio examples",
  "developer with AI projects",
  "SEO optimized portfolio site",
  "how to build a developer portfolio",
  "showcase coding projects",
  "web development trends 2025",
  "computer science student projects",
  "B.Tech Computer Science portfolio",
  "hire Next.js developer",
  "hire React developer",
  "internship software development",
  "student developer looking for job",

  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Next.js",
  "React",
  "Tailwind",
  "Framer Motion",
  "PostgreSQL",
  "MongoDB",
  "Oracle SQL",
  "MySQL",
  "Jest",
  "Vercel",
  "GitHub Actions",
  "API routes",
  "app router",
  "responsive UI",
  "dark mode toggle",
  "UI/UX",
  "full-stack",
  "AI",
  "Machine Learning",
  "Cloud Computing",
  "Firebase",
  "GraphQL",
  "REST API",
  "WebSockets",
  "Git",
  "GitHub",
  "VS Code",
  "Node.js",
  "Express.js",
  "Python",
  "C",
  "C++",
  "Java",
  "Data Structures and Algorithms",
  "DSA",
  "Object-Oriented Programming",
  "OOP",
  "System Design",
  "Agile development",
  "Clean Code",
  "Scalable architecture",
];
